---
- name: Install wigglecam via pipx into system Python
  hosts: all   # oder 'all', je nach Inventar
  become: true

  tasks:
    - name: Ensure pipx is installed
      apt:
        name: pipx
        state: present
        update_cache: yes
    - name: Ensure apps prerequisites are installed
      apt:
        name:
          - python3-dev
          - python3-venv
          - python3-pip
          - build-essential
          - libnng-dev 
        state: present
        update_cache: yes

    - name: Install wigglecam with pipx into system Python
      environment:
        TMPDIR: /var/tmp # use /var/tmp instead default /tmp because on pi zero it will run out of space.
      command: >
        pipx install --system-site-packages wigglecam[node]
      args:
        creates: /home/pi/.local/pipx/venvs/wigglecam-node # to avoid reinstallation every time.

